cc_library(
    name = "classification",
    srcs = [
        "ClassificationEnvironment.h",
        "FormulaCodon.h",
        "FormulaEntity.h",
        "FormulaEntityMutator.h",
    ],
    hdrs = [
    ],
    deps = [
        "//lib/assert:assert",
        "//lib/tensor:tensor",
        "//lib/util:utils"
    ],
    visibility = ["//visibility:public"],
)