cc_library(
    name = "selectors",
    srcs = [
        "ArenaSelector.h",
    ],
    hdrs = [
    ],
    deps = [
        "//lib/assert:assert",
        "//lib/util:utils"
    ],
    visibility = ["//visibility:public"],
)